name: Example Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get default branch name
        run: |
          const ref = process.env.GITHUB_REF;
          const parts = ref.split('/');
          const defaultBranchName = parts[parts.length - 1];
          echo "The default branch name is ${defaultBranchName}"
